name = "dawnmon-modpack"
author = "SoniaSquishy & Shebang"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f941d9e32bbee6a761e81eb17e0258fbb3075d05f7101e149401db936297bce"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
