name = "dawnmon-modpack"
author = "SoniaSquishy & Shebang"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6852206b1729450900b61d08cef14b780cbae8bd1ea1be026d0a2dec3909c5ef"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
