name = "dawnmon-modpack"
author = "SoniaSquishy & Shebang"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71c75ecaee2cc79a00b29da4a92ab20b906816d151dbb1ce6f7c1add91f9c56a"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
